# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- release

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '*Droid.sln'
    feedsToUse: 'select'

- task: android-manifest-package-name@1
  inputs:
    sourcePath: 'StorjPhotoGalleryUploader.Droid/Properties/AndroidManifest.xml'
    packageName: 'io.storj.photogalleryuploader'
    appLabel: 'Storj Photo Gallery Uploader'
    printFile: true

- task: android-manifest-version@1
  inputs:
    sourcePath: 'StorjPhotoGalleryUploader.Droid/Properties/AndroidManifest.xml'
    versionCodeOption: 'buildid'
    versionCode: '$(Build.BuildId)'
    printFile: true

- task: XamarinAndroid@1
  inputs:
    projectFile: '*Droid.sln'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    jdkOption: 'JDKVersion'

- task: AndroidSigning@3
  displayName: 'Signing and aligning APK file(s) **/*.apk'
  inputs:
    apksignerKeystoreFile: StorjPhotoGalleryUploader.keystore
    apksignerKeystorePassword: '$(keystore.password)'
    apksignerKeystoreAlias: '$(keystore.alias)'
    apksignerKeyPassword: '$(keystore.keypassword)'
    apksignerArguments: --out $(outputDirectory)/io.storj.photogalleryuploader.release.apk

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(outputDirectory)'
    Contents: '*io.storj.photogalleryuploader.release.apk'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'android_storeupload_drop'
    publishLocation: 'Container'